connecting to Carbon at 127.0.0.1:2003 (localhost)
2014-06-24 17:15:01.216 PostAuctionService ./rtbkit/core/post_auction/post_auction_service.cc:114 - void RTBKIT::PostAuctionService::initMatcher(size_t) [1;31mCreating SimpleEventMatcher[0m
2014-06-24 17:15:01.230 PostAuctionService ./rtbkit/core/post_auction/post_auction_service.cc:156 - void RTBKIT::PostAuctionService::initConnections() [1;31mpost auction logger on PostAuctionLoop/logger[0m
2014-06-24 17:15:01.264 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to agentConfigurationService/listen[0m
2014-06-24 17:15:01.269 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://127.0.0.1:19000[0m
2014-06-24 17:15:01.271 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to monitor/zeromq[0m
2014-06-24 17:15:01.273 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://127.0.0.1:24000[0m
2014-06-24 17:15:01.276 PostAuctionService ./rtbkit/core/post_auction/post_auction_runner.cc:96 - void RTBKIT::PostAuctionRunner::init() [1;31mwin timeout is 3600[0m
2014-06-24 17:15:01.277 PostAuctionService ./rtbkit/core/post_auction/post_auction_runner.cc:97 - void RTBKIT::PostAuctionRunner::init() [1;31mauction timeout is 900[0m
2014-06-24 17:15:01.339 PostAuctionService ./rtbkit/core/post_auction/post_auction_runner.cc:149 - RTBKIT::PostAuctionService::Stats report(const RTBKIT::PostAuctionService&, double, const RTBKIT::PostAuctionService::Stats&) [1;31m
  0.00  bids/sec
  0.00  events/sec
  0.00  wins/sec
184.47? loss/sec
  0.00  unmatched
  0.00  errors[0m
got configuration message fixed-price-agent-ex_7300
********* calling addSpendAccount for hello:world for SlaveBanker PostAuctionLoop.slaveBanker
error: exception in context Banker addSpendAccount
error: exception in context Banker addSpendAccount
error: exception in context Banker addSpendAccount
error: exception in context Banker addSpendAccount
exception processing source slave-banker
terminate called after throwing an instance of 'ML::Exception'
  what():  connection to '' is unavailable
