connecting to Carbon at 127.0.0.1:2003 (localhost)
zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists

--------------------------[Exception thrown]---------------------------
time:   2014-06-24T17:16:02
type:   ML::Exception
pid:    7570; tid: 7570
what:   Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists
stack:
00: 0x0x7f377423edb7 at __cxa_throw + 0x27 in /home/krzysztof/rtbkit/build/x86_64/bin/../bin/libexception_hook.so + 0xdb7/home/krzysztof/rtbkit/build/x86_64/bin/../bin/libexception_hook.so(__cxa_throw+0x27) [0x7f377423edb7]
01: 0x0x7f3772331553 at Datacratic::ZookeeperConnection::checkRes(int, int&, char const*, char const*) + 0xe3 in /home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x118553/home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection8checkResEiRiPKcS3_+0xe3) [0x7f3772331553]
02: 0x0x7f3772331151 at Datacratic::ZookeeperConnection::createNode(std::string const&, std::string const&, bool, bool, bool, bool) + 0x441 in /home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x118151/home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection10createNodeERKSsS2_bbbb+0x441) [0x7f3772331151]
03: 0x0x7f37722e8cd5 at Datacratic::ZookeeperConfigurationService::setUnique(std::string const&, Json::Value const&) + 0x285 in /home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xcfcd5/home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic29ZookeeperConfigurationService9setUniqueERKSsRKN4Json5ValueE+0x285) [0x7f37722e8cd5]
04: 0x0x7f37722d3d84 at Datacratic::ServiceBase::registerServiceProvider(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) + 0x1c4 in /home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xbad84/home/krzysztof/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic11ServiceBase23registerServiceProviderERKSsRKSt6vectorISsSaISsEE+0x1c4) [0x7f37722d3d84]
05: 0x0x7f3773b48784 at RTBKIT::Router::init() + 0xd4 in /home/krzysztof/rtbkit/build/x86_64/bin/../bin/librtb_router.so + 0x7c784/home/krzysztof/rtbkit/build/x86_64/bin/../bin/librtb_router.so(_ZN6RTBKIT6Router4initEv+0xd4) [0x7f3773b48784]
06: 0x0x42518f at RTBKIT::RouterRunner::init() + 0x3df in build/x86_64/bin/nullbanker_router_runner + 0x2518fbuild/x86_64/bin/nullbanker_router_runner(_ZN6RTBKIT12RouterRunner4initEv+0x3df) [0x42518f]
07: 0x0x4231fe at main + 0x6e in build/x86_64/bin/nullbanker_router_runner + 0x231febuild/x86_64/bin/nullbanker_router_runner(main+0x6e) [0x4231fe]
08: 0x0x7f3772ca976d at __libc_start_main + 0xed in /lib/x86_64-linux-gnu/libc.so.6 + 0x2176d/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f3772ca976d]
09: 0x0x4239e5 in build/x86_64/bin/nullbanker_router_runner + 0x239e5build/x86_64/bin/nullbanker_router_runner() [0x4239e5]

terminate called after throwing an instance of 'ML::Exception'
  what():  Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists
